name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Compute BASE_URL
        run: |
          if [[ "${{ github.repository }}" == *".github.io" ]]; then
            echo "BASE_URL=/" >> $GITHUB_ENV
          else
            REPO="${{ github.event.repository.name }}"
            echo "BASE_URL=/$REPO/" >> $GITHUB_ENV
          fi
      - run: npm run build
        env:
          BASE_URL: ${{ env.BASE_URL }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
